# Generated by Django 3.1.3 on 2020-11-08 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Product title')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Price')),
                ('model', models.CharField(max_length=100, verbose_name='Apple Watch')),
                ('compatibility', models.CharField(max_length=100, verbose_name='Compatibility')),
                ('battery', models.CharField(max_length=1000, verbose_name='Battery')),
                ('moistureResistance', models.CharField(max_length=1000, verbose_name='Moisture resistance')),
                ('otherInfo', models.CharField(max_length=1000, verbose_name='Other information')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.categoty', verbose_name='Category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Iphone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Product title')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Price')),
                ('model', models.CharField(max_length=100, verbose_name='IPhone')),
                ('display', models.CharField(max_length=1000, verbose_name='Display')),
                ('processor', models.CharField(max_length=1000, verbose_name='Processor')),
                ('memorySize', models.CharField(max_length=1000, verbose_name='Memory size')),
                ('battery', models.CharField(max_length=1000, verbose_name='Battery')),
                ('weight', models.CharField(max_length=1000, verbose_name='Weight')),
                ('otherInfo', models.CharField(max_length=1000, verbose_name='Other information')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.categoty', verbose_name='Category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
